/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import BaseDeDatos.UsuarioDAO;
import Excepciones.DataAccessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandrux
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
    }

    
    
    
    
    public void iniciarSesion() throws DataAccessException{
            if (usuario.getText().isEmpty() || pass.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Error: Usuario y/o Contraseña vacios");
            } else {
                UsuarioDAO usuarioDAO = new UsuarioDAO();
                String cont = usuarioDAO.buscarcontraseña(usuario.getText());//me devuelve la contraseña de la db
                String tipo = usuarioDAO.buscartipo(usuario.getText());//me devuelve el tipo, docente o alumno

                if (pass.getText().equals(cont) && tipo.equals("Docente")) {

                    MenuDocente v = new MenuDocente(Usu());
                    v.setVisible(true);
                    dispose();
                    
                } else if (pass.getText().equals(cont) && tipo.equals("Alumno")) {
                    MenuAlumno v = new MenuAlumno();
                    v.setVisible(true);
                    //v.id_usuario = usuario.getText();
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario y/o Contraseña invalidas");
                }
            }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuario = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        registrarme = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        olvide = new javax.swing.JLabel();
        iniciarsesion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 170, -1));
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 170, -1));

        registrarme.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registrarme.setForeground(new java.awt.Color(0, 0, 204));
        registrarme.setText("Registrarse");
        registrarme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarmeMouseClicked(evt);
            }
        });
        getContentPane().add(registrarme, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        jLabel4.setText("¿Aún no eres Usuario?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        olvide.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        olvide.setForeground(new java.awt.Color(0, 0, 255));
        olvide.setText("Olvidé mi contraseña");
        olvide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                olvideMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                olvideMouseExited(evt);
            }
        });
        getContentPane().add(olvide, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, 20));

        iniciarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iniciar sesión1.jpg"))); // NOI18N
        iniciarsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarsesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iniciarsesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iniciarsesionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iniciarsesionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                iniciarsesionMouseReleased(evt);
            }
        });
        getContentPane().add(iniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/00_Inicio.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarsesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarsesionMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Recursos/Iniciar sesión2.png"));
        iniciarsesion.setIcon(II);
    }//GEN-LAST:event_iniciarsesionMousePressed

    private void iniciarsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarsesionMouseClicked
                try {
                    iniciarSesion();
                } catch (DataAccessException ex) {
                    new DataAccessException("Error en IniciarSesion() " + ex);
                }
    }//GEN-LAST:event_iniciarsesionMouseClicked

    private void iniciarsesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarsesionMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Recursos/Iniciar sesión2.png"));
        iniciarsesion.setIcon(II);
    }//GEN-LAST:event_iniciarsesionMouseEntered

    private void iniciarsesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarsesionMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Recursos/Iniciar sesión1.jpg"));
        iniciarsesion.setIcon(II);
    }//GEN-LAST:event_iniciarsesionMouseExited

    private void iniciarsesionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarsesionMouseReleased
////     
    }//GEN-LAST:event_iniciarsesionMouseReleased

    private void olvideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olvideMouseClicked
                if (evt.getSource() == olvide) { 
                    //VentanaRestaurarUsuario v = new VentanaRestaurarUsuario();
                    RestaurarUsuario v = new RestaurarUsuario();
                    v.setVisible(true);
                }
    }//GEN-LAST:event_olvideMouseClicked

    private void registrarmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarmeMouseClicked
             if (evt.getSource() == registrarme) {      
                 try {
                     AltaUsuario v = new AltaUsuario();
                 } catch (DataAccessException ex) {
                     Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
    }//GEN-LAST:event_registrarmeMouseClicked

    private void olvideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olvideMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_olvideMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iniciarsesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel olvide;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel registrarme;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
    
    public String Usu(){
        String u = usuario.getText();
        return u;
    }
}
